image:
  repo: "cassandra"
  tag: "3"
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP

persistence:
  enabled: true
  storageClass: "default"
  accessMode: ReadWriteOnce
  size: 256Gi

resources:
  requests:
    memory: 4Gi
    cpu: .5
  limits:
    memory: 4Gi
    cpu: 2

config:
  cluster_name: cassandra
  cluster_size: 3
  seed_size: 2
  num_tokens: 256
  dc_name: DC1
  rack_name: RAC1
  endpoint_snitch: SimpleSnitch
  max_heap_size: 2048M
  heap_new_size: 512M
  start_rpc: false
  ports:
    cql: 9042
    thrift: 9160
podLabels:
  component: cassandra

podSettings:
  terminationGracePeriodSeconds: 30

podManagementPolicy: OrderedReady
updateStrategy:
  type: OnDelete

securityContext:
  enabled: false
  fsGroup: 999
  runAsUser: 999

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpression:
          - key: component
            operator: In
            values:
            - cassandra
        topologyKey: kubernetes.io/hostname

